package com.hj.dao;

import java.util.List;

import com.hj.entity.Computers;

public interface ComputersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table computers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table computers
     *
     * @mbggenerated
     */
    int insert(Computers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table computers
     *
     * @mbggenerated
     */
    Computers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table computers
     *
     * @mbggenerated
     */
    List<Computers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table computers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Computers record);
    
}