package com.hj.dao;

import com.hj.entity.Consumelogs;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ConsumelogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    int insert(Consumelogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    Consumelogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    List<Consumelogs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Consumelogs record);
    
    /**
     * 	根据卡号查询记录
     * @return
     */
    List<Consumelogs> queryBycardNo(@Param("cardNo")String cardNo);
    
    /**
     * 	连接阅览室查询
     * @return
     */
    List<Consumelogs> queryJoinReadrooms();


}