package com.hj.dao;

import com.hj.entity.Readrooms;
import java.util.List;

public interface ReadroomsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    int insert(Readrooms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    Readrooms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    List<Readrooms> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Readrooms record);
    
    
    /**
     * 	查询除去id为0的所有阅览室
     * @return
     */
    List<Readrooms> selectNo();
}