package com.hj.dao;

import com.hj.entity.Statistics;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface StatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    int insert(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    Statistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    List<Statistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Statistics record);
    
    /**
     *	批量添加刷卡记录(用于任务调度)
     * @return
     */
    int insertAll();
    
    /**
     * 	根据时间查询
     * @return
     */
    List<Statistics> queryByTime(@Param("ksTime")String ksTime,@Param("jsTime")String jsTime,@Param("rId")Integer rId);
    
    
}