package com.hj.dao;

import com.hj.entity.Teachers;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TeachersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbggenerated
     */
    int insert(Teachers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbggenerated
     */
    Teachers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbggenerated
     */
    List<Teachers> selectAll(@Param("name")String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Teachers record);
}