package com.hj.entity;

import java.io.Serializable;

public class Computers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column computers.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column computers.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column computers.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column computers.readroomId
     *
     * @mbggenerated
     */
    private Integer readroomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column computers.remake
     *
     * @mbggenerated
     */
    private String remake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table computers
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column computers.id
     *
     * @return the value of computers.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column computers.id
     *
     * @param id the value for computers.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column computers.name
     *
     * @return the value of computers.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column computers.name
     *
     * @param name the value for computers.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column computers.ip
     *
     * @return the value of computers.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column computers.ip
     *
     * @param ip the value for computers.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column computers.readroomId
     *
     * @return the value of computers.readroomId
     *
     * @mbggenerated
     */
    public Integer getReadroomid() {
        return readroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column computers.readroomId
     *
     * @param readroomid the value for computers.readroomId
     *
     * @mbggenerated
     */
    public void setReadroomid(Integer readroomid) {
        this.readroomid = readroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column computers.remake
     *
     * @return the value of computers.remake
     *
     * @mbggenerated
     */
    public String getRemake() {
        return remake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column computers.remake
     *
     * @param remake the value for computers.remake
     *
     * @mbggenerated
     */
    public void setRemake(String remake) {
        this.remake = remake == null ? null : remake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table computers
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", ip=").append(ip);
        sb.append(", readroomid=").append(readroomid);
        sb.append(", remake=").append(remake);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}