package com.hj.entity;

public class Statistics  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.readroomId
     *
     * @mbggenerated
     */
    private Integer readroomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.peopleNums
     *
     * @mbggenerated
     */
    private Integer peoplenums;

    private String time;

    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getReadroomid() {
		return readroomid;
	}

	public void setReadroomid(Integer readroomid) {
		this.readroomid = readroomid;
	}

	public Integer getPeoplenums() {
		return peoplenums;
	}

	public void setPeoplenums(Integer peoplenums) {
		this.peoplenums = peoplenums;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Override
	public String toString() {
		return "Statistics [id=" + id + ", readroomid=" + readroomid + ", peoplenums=" + peoplenums + ", time=" + time
				+ "]";
	}

	
}