package com.hj.entity;

import java.io.Serializable;

public class Teachers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.cardNo
     *
     * @mbggenerated
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.sectionId
     *
     * @mbggenerated
     */
    private Integer sectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.remake
     *
     * @mbggenerated
     */
    private String remake;
    
    /**
     * 科室名称
     */
    private String ksName;
    /**
     * 状态名称
     */
    private String statusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teachers
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.id
     *
     * @return the value of teachers.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.id
     *
     * @param id the value for teachers.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.cardNo
     *
     * @return the value of teachers.cardNo
     *
     * @mbggenerated
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.cardNo
     *
     * @param cardno the value for teachers.cardNo
     *
     * @mbggenerated
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.name
     *
     * @return the value of teachers.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.name
     *
     * @param name the value for teachers.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.sex
     *
     * @return the value of teachers.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.sex
     *
     * @param sex the value for teachers.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.sectionId
     *
     * @return the value of teachers.sectionId
     *
     * @mbggenerated
     */
    public Integer getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.sectionId
     *
     * @param sectionid the value for teachers.sectionId
     *
     * @mbggenerated
     */
    public void setSectionid(Integer sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.status
     *
     * @return the value of teachers.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.status
     *
     * @param status the value for teachers.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.remake
     *
     * @return the value of teachers.remake
     *
     * @mbggenerated
     */
    public String getRemake() {
        return remake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.remake
     *
     * @param remake the value for teachers.remake
     *
     * @mbggenerated
     */
    public void setRemake(String remake) {
        this.remake = remake == null ? null : remake.trim();
    }

	public String getKsName() {
		return ksName;
	}

	public void setKsName(String ksName) {
		this.ksName = ksName;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}
	
	

	

	public Teachers(Integer id, Integer status) {
		super();
		this.id = id;
		this.status = status;
	}

	public Teachers() {
		super();
	}

	@Override
	public String toString() {
		return "Teachers [id=" + id + ", cardno=" + cardno + ", name=" + name + ", sex=" + sex + ", sectionid="
				+ sectionid + ", status=" + status + ", remake=" + remake + ", ksName=" + ksName + ", statusName="
				+ statusName + "]";
	}

    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbggenerated
     */
	
	
}