spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/jfinaldemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.hj.dao: debug 
 
    
